name: Build and package

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - master
      - release/**
    tags:
      - "*"
  pull_request:
    branches: 
      - main
      - master

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x

      - uses: dotnet/nbgv@master
        id: nbgv
      
      - name: Build packages
        shell: pwsh
        run: |
          dotnet pack -c Release -o ./artifacts -p:PackageVersion=${{ steps.nbgv.outputs.NuGetPackageVersion }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        
      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: |
            ./artifacts/*.nupkg

      - name: Publish to nuget
        if: github.ref_name == 'master' || startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          dotnet nuget push "./artifacts/*.nupkg" -k $Env:NUGET_KEY -s https://api.nuget.org/v3/index.json
